version: "3.4"

networks:
  backend:
    external: true
    name: "backend"
  frontend:
    external: true
    name: "frontend"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/var/www/html
    networks:
      - backend
      - frontend
    environment:
      # See https://xdebug.org/docs/all_settings#mode 
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      # See https://xdebug.org/docs/all_settings#XDEBUG_CONFIG
      XDEBUG_CONFIG: "${XDEBUG_CONFIG:-}"

  web:
    volumes:
      - ./:/var/www/html
    networks:
      - frontend
