version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  web:
    build:
      context: .
      target: app_nginx
    hostname: product-server
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php

volumes:
  php_socket:
